/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TodoApp;

import Util.ConnectionFactory;
import controller.ProjectController;
import controller.TaskController;
import java.sql.Connection;
import java.util.Date;
import java.util.List;
import java.util.function.Consumer;
import model.Project;
import model.Task;



public class App {
    public String getGreeting() {
        ProjectController prcon = new ProjectController();
////        
//        Project projectOne = new Project(); 
//        projectOne.setName("faculdade");
//        projectOne.setUpdatedAt(new Date());
//        projectOne.setDescription("Estudar Java");
//       
//        prcon.saveProject(projectOne);
//        
//        projectOne.setName("novo nome");
//        System.out.println(projectOne.getName());
//        
//        prcon.updateProject(projectOne);
        

//       System.out.println(projectOne.getId());
//        
//        
//        
//       System.out.println(prcon.getAllProjects());
//          projectOne.setName("novo nome");
//
          //prcon.updateProject(projectOne);
          
//         Project p1 = new Project();
//         p1.setUpdatedAt(new Date());
//         p1.setDescription("Estudar Python");
//         p1.setName("Python");
       
//         prcon.saveProject(p1);
//          
//          Task task = new Task();
//          TaskController tasC = new TaskController();
//         
//          task.setDescription("devem ser qualquer coisa");
//          task.setName("Estudar Orientao a Objetos");
//          task.setIdProject(1);
//          task.setCompleted(false);
//          task.setDeadLine(new Date());
//          task.setCreatedAt(new Date());
//          task.setUpdatedAt(new Date());
//          
//          
//          
//          //tasC.update(task);
//          
//          task.setCompleted(false);
//          task.setName("hjhj");
//          task.setId(3);
//          
//          tasC.update(task);

////          
//         tasC.removeById(2);

//            Consumer<Task> imprimir = tarefa -> System.out.println(tarefa);
//            
//            List<Task> tarefas = tasC.getAllTask(1);
//            tarefas.stream().forEach(imprimir);
         
        
////          

          //tasC.save(task);
//      
//          task.setName("brunobarcelos");
//          task.setId(3);
//          System.out.println(task.getName());
//          System.out.println(task.getId());
//          System.out.println(task);
//          tasC.update(task);

           
        return "";
    }

    public static void main(String[] args) {
       System.out.println(new App().getGreeting());
       
    }
}
