/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Util.ButtonColumnCellRenderer;
import Util.DeadLineColumnCellRenderer;
import Util.TaskTableModel;
import controller.ProjectController;
import controller.TaskController;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.DefaultListModel;
import model.Project;
import model.Task;

/**
 *
 * @author Bruno
 */
public class MainScreen extends javax.swing.JFrame {

    ProjectController projectController;
    TaskController taskController;
    
    DefaultListModel projectsModel;
    TaskTableModel tasksModel;
    
    public MainScreen() {
        initComponents();

        initDataController();
        initComponentsModel();
        decoretTableTask();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3EmptyList = new javax.swing.JPanel();
        jLabel1EmptyListIcon = new javax.swing.JLabel();
        jLabel2EmptyListTitle = new javax.swing.JLabel();
        jLabel3EmptyListSubTitle = new javax.swing.JLabel();
        jPanel1Toolbar = new javax.swing.JPanel();
        jLabel1ToolbarTitle = new javax.swing.JLabel();
        jLabel2ToolbarSubTitle = new javax.swing.JLabel();
        jPanel3Projects = new javax.swing.JPanel();
        jLabel3ProjectsTitle = new javax.swing.JLabel();
        jButton1ProjectsAdd = new javax.swing.JButton();
        jPanel4Tasks = new javax.swing.JPanel();
        jLabel4TasksTitle = new javax.swing.JLabel();
        jButton4TasksAdd = new javax.swing.JButton();
        jPanel5ProjectsList = new javax.swing.JPanel();
        jScrollPane1Projects = new javax.swing.JScrollPane();
        jList1Projects = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTasks = new javax.swing.JTable();

        jPanel3EmptyList.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1EmptyListIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1EmptyListIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lists.png"))); // NOI18N

        jLabel2EmptyListTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2EmptyListTitle.setForeground(new java.awt.Color(0, 153, 102));
        jLabel2EmptyListTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2EmptyListTitle.setText("Nenhuma tarefa por aqui :D");

        jLabel3EmptyListSubTitle.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3EmptyListSubTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3EmptyListSubTitle.setText("Clique no botão \"+\" para adicionar uma nova tarefa");

        javax.swing.GroupLayout jPanel3EmptyListLayout = new javax.swing.GroupLayout(jPanel3EmptyList);
        jPanel3EmptyList.setLayout(jPanel3EmptyListLayout);
        jPanel3EmptyListLayout.setHorizontalGroup(
            jPanel3EmptyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1EmptyListIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2EmptyListTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3EmptyListSubTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3EmptyListLayout.setVerticalGroup(
            jPanel3EmptyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3EmptyListLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel1EmptyListIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2EmptyListTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3EmptyListSubTitle)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(600, 600));

        jPanel1Toolbar.setBackground(new java.awt.Color(0, 153, 102));
        jPanel1Toolbar.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1ToolbarTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1ToolbarTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1ToolbarTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tick.png"))); // NOI18N
        jLabel1ToolbarTitle.setText(" App Tarefas");

        jLabel2ToolbarSubTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2ToolbarSubTitle.setText("Anote tudo, não esqueça nada");

        javax.swing.GroupLayout jPanel1ToolbarLayout = new javax.swing.GroupLayout(jPanel1Toolbar);
        jPanel1Toolbar.setLayout(jPanel1ToolbarLayout);
        jPanel1ToolbarLayout.setHorizontalGroup(
            jPanel1ToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1ToolbarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1ToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1ToolbarLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2ToolbarSubTitle))
                    .addComponent(jLabel1ToolbarTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1ToolbarLayout.setVerticalGroup(
            jPanel1ToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1ToolbarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1ToolbarTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2ToolbarSubTitle)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel3Projects.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3Projects.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3ProjectsTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3ProjectsTitle.setForeground(new java.awt.Color(0, 153, 102));
        jLabel3ProjectsTitle.setText("Projetos");

        jButton1ProjectsAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        jButton1ProjectsAdd.setBorder(null);
        jButton1ProjectsAdd.setContentAreaFilled(false);
        jButton1ProjectsAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1ProjectsAddMouseClicked(evt);
            }
        });
        jButton1ProjectsAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ProjectsAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3ProjectsLayout = new javax.swing.GroupLayout(jPanel3Projects);
        jPanel3Projects.setLayout(jPanel3ProjectsLayout);
        jPanel3ProjectsLayout.setHorizontalGroup(
            jPanel3ProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3ProjectsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3ProjectsTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1ProjectsAdd)
                .addContainerGap())
        );
        jPanel3ProjectsLayout.setVerticalGroup(
            jPanel3ProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3ProjectsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3ProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1ProjectsAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3ProjectsTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanel4Tasks.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4Tasks.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4TasksTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4TasksTitle.setForeground(new java.awt.Color(0, 153, 102));
        jLabel4TasksTitle.setText("Tarefas");

        jButton4TasksAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        jButton4TasksAdd.setBorder(null);
        jButton4TasksAdd.setContentAreaFilled(false);
        jButton4TasksAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4TasksAddMouseClicked(evt);
            }
        });
        jButton4TasksAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4TasksAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4TasksLayout = new javax.swing.GroupLayout(jPanel4Tasks);
        jPanel4Tasks.setLayout(jPanel4TasksLayout);
        jPanel4TasksLayout.setHorizontalGroup(
            jPanel4TasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4TasksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4TasksTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4TasksAdd)
                .addGap(15, 15, 15))
        );
        jPanel4TasksLayout.setVerticalGroup(
            jPanel4TasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4TasksLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4TasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4TasksAdd)
                    .addComponent(jLabel4TasksTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5ProjectsList.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5ProjectsList.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jList1Projects.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jList1Projects.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1Projects.setToolTipText("");
        jList1Projects.setFixedCellHeight(50);
        jList1Projects.setSelectionBackground(new java.awt.Color(0, 153, 102));
        jList1Projects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1ProjectsMouseClicked(evt);
            }
        });
        jScrollPane1Projects.setViewportView(jList1Projects);

        javax.swing.GroupLayout jPanel5ProjectsListLayout = new javax.swing.GroupLayout(jPanel5ProjectsList);
        jPanel5ProjectsList.setLayout(jPanel5ProjectsListLayout);
        jPanel5ProjectsListLayout.setHorizontalGroup(
            jPanel5ProjectsListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5ProjectsListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1Projects, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5ProjectsListLayout.setVerticalGroup(
            jPanel5ProjectsListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5ProjectsListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1Projects)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jTableTasks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Decrição", "Prazo", "Tarefa Concluida"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTasks.setRowHeight(40);
        jTableTasks.setSelectionBackground(new java.awt.Color(153, 255, 153));
        jTableTasks.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableTasks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTasksMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableTasks);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5ProjectsList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3Projects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4Tasks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPanel1Toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1Toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3Projects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4Tasks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5ProjectsList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ProjectsAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ProjectsAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ProjectsAddActionPerformed

    private void jButton4TasksAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4TasksAddActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton4TasksAddActionPerformed

    private void jButton1ProjectsAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1ProjectsAddMouseClicked
        // TODO add your handling code here:
        // botao add das tarefas evento de clique
        ProjectDialogScreen projectDialogScreen = new ProjectDialogScreen(this, rootPaneCheckingEnabled);
        projectDialogScreen.setVisible(true);
        
        projectDialogScreen.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e ) {
                loadProjects();
                         
            }
        
        
        });
    }//GEN-LAST:event_jButton1ProjectsAddMouseClicked

    private void jButton4TasksAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4TasksAddMouseClicked
        // TODO add your handling code here:
        TaskDialogScreen taskDialogScreen = new TaskDialogScreen(this, rootPaneCheckingEnabled);
        
        // setando na tarefa o projeto que ela pertence
        int projectIndex = jList1Projects.getSelectedIndex();
        Project project = (Project) projectsModel.get(projectIndex);
        taskDialogScreen.setProjectTask(project);
        

        taskDialogScreen.setVisible(true);
        
        
        taskDialogScreen.addWindowListener(new WindowAdapter() {
            public void windowClosed(WindowEvent e ) {
                int projectIndex = jList1Projects.getSelectedIndex();
                Project project = (Project) projectsModel.get(projectIndex);
                loadTasks(project.getId());
                         
            }
        });
       
    }//GEN-LAST:event_jButton4TasksAddMouseClicked

    private void jTableTasksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTasksMouseClicked
        // TODO add your handling code here:
        // evento de clicar na tabela
        // pegando em que ponto ocorreu o clik, linha e column
        int rowIndex = jTableTasks.rowAtPoint(evt.getPoint());
        int columnIndex = jTableTasks.columnAtPoint(evt.getPoint());
        Task task = tasksModel.getTasks().get(rowIndex);
        
        switch(columnIndex) {
            
            case 3:           
                taskController.update(task);
                break;
            case 5:
                taskController.removeById(task.getId());
                tasksModel.getTasks().remove(task);  
                
                int projectIndex = jList1Projects.getSelectedIndex();
                Project project = (Project) projectsModel.get(projectIndex);
                loadTasks(project.getId());
                break;               
        }
  
    }//GEN-LAST:event_jTableTasksMouseClicked

    private void jList1ProjectsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1ProjectsMouseClicked
        // TODO add your handling code here:
        // evento de selecionar um projeto na lista
        
        int projectIndex = jList1Projects.getSelectedIndex();
        Project project = (Project) projectsModel.get(projectIndex);
        loadTasks(project.getId());
  
    }//GEN-LAST:event_jList1ProjectsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1ProjectsAdd;
    private javax.swing.JButton jButton4TasksAdd;
    private javax.swing.JLabel jLabel1EmptyListIcon;
    private javax.swing.JLabel jLabel1ToolbarTitle;
    private javax.swing.JLabel jLabel2EmptyListTitle;
    private javax.swing.JLabel jLabel2ToolbarSubTitle;
    private javax.swing.JLabel jLabel3EmptyListSubTitle;
    private javax.swing.JLabel jLabel3ProjectsTitle;
    private javax.swing.JLabel jLabel4TasksTitle;
    private javax.swing.JList<String> jList1Projects;
    private javax.swing.JPanel jPanel1Toolbar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3EmptyList;
    private javax.swing.JPanel jPanel3Projects;
    private javax.swing.JPanel jPanel4Tasks;
    private javax.swing.JPanel jPanel5ProjectsList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane1Projects;
    private javax.swing.JTable jTableTasks;
    // End of variables declaration//GEN-END:variables
    
    public void decoretTableTask(){
        // Customizar a tabela de tarefas
        jTableTasks.getTableHeader().setFont(new Font("Segoi UI", Font.BOLD, 14));
        jTableTasks.getTableHeader().setBackground(new Color(0,153,102));
        jTableTasks.getTableHeader().setForeground(new Color(255,255,255));
        
        // personalizando a coluna 2 prazo 
        jTableTasks.getColumnModel().getColumn(2).setCellRenderer(new DeadLineColumnCellRenderer());
        // personalizando a coluna4 e 5 botao editar e excluir
        jTableTasks.getColumnModel().getColumn(4).
                setCellRenderer(new ButtonColumnCellRenderer("edit"));
        jTableTasks.getColumnModel().getColumn(5).
                setCellRenderer(new ButtonColumnCellRenderer("delete"));
        
        
        
        
        // ordenando a lista automaticamente
        jTableTasks.setAutoCreateRowSorter(true);
    }
    
    public void initDataController(){
        projectController = new ProjectController();
        taskController = new TaskController();
    
    }
    
    public void initComponentsModel(){
        // inicializando o model para fazer a parte de apresentação dos projetos
        this.projectsModel = new DefaultListModel<>();
        loadProjects();
        
        tasksModel = new TaskTableModel();
        jTableTasks.setModel(tasksModel);
        
        // selecionar o primeiro projeto da lista
        if (!projectsModel.isEmpty()) {
            jList1Projects.setSelectedIndex(0);
            Project project = (Project) projectsModel.get(0);
            loadTasks(project.getId());
        }
    }
    
    private void showJTableTasks(boolean hasTasks) {
    // metodo que carrega as tarefas quando tem tarefas
        
        if (hasTasks) {
            if(jPanel3EmptyList.isVisible()) {
                jPanel3EmptyList.setVisible(false);
                jPanel3EmptyList.remove(jPanel3EmptyList);
        
            }
            
            jPanel2.add(jScrollPane1);
            jScrollPane1.setVisible(true);
            jScrollPane1.setSize(jPanel2.getWidth(), jPanel2.getHeight());
        
        }else{
            // se nao tem tarefas
            if (jScrollPane1.isVisible()){
                jScrollPane1.setVisible(false);
                jPanel2.remove(jScrollPane1);
            
            }
             jPanel2.add(jPanel3EmptyList);
             jPanel3EmptyList.setVisible(true);
             jPanel3EmptyList.setSize(jPanel2.getWidth(), jPanel2.getHeight());
             
        }

    }
    

    
    public void loadTasks(int idProject){
        List<Task> tasks = taskController.getAllTask(idProject);
        this.tasksModel.setTasks(tasks);
        showJTableTasks(!tasks.isEmpty());
        
    }
    
    public void loadProjects(){
        List<Project> listProjects = this.projectController.getAllProjects();
              
        projectsModel.clear();
        
        for (int i = 0; i < listProjects.size(); i++) {
            Project project = listProjects.get(i);
            projectsModel.addElement(project);
        }
        
        jList1Projects.setModel(projectsModel);
        
    }
}
